[package]
name = "swc-conformance"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
swc_core = { version = "77.0.2", features = [
    "common",
    "ecma_ast",
    "ecma_parser",
    "ecma_parser_typescript",
    "ecma_transforms",
    "ecma_visit",
] }
walkdir = "2.5.0"
